# Generated by Django 3.0.8 on 2020-07-13 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200713_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 14, 9, 36, 96179)),
        ),
    ]
