# Generated by Django 3.0.8 on 2020-07-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passeduserquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeduserquiz',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passeduserquiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
