# Generated by Django 3.0.8 on 2020-07-14 18:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200714_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
