# Generated by Django 3.0.8 on 2020-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200714_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeduserquiz',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='passeduserquiz',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Счет'),
        ),
    ]
